"""Añadir fk proveedor_id a la tabla Servicio

Revision ID: 711fb62304c6
Revises: a3e30ff9777c
Create Date: 2025-11-01 11:43:26.842752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711fb62304c6'
down_revision = 'a3e30ff9777c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ID_PROVEEDOR_VALIDO = 101

    op.add_column('servicio', sa.Column('proveedor_id', sa.Integer(), nullable=True))

    op.execute(f"UPDATE servicio SET proveedor_id = {ID_PROVEEDOR_VALIDO} WHERE proveedor_id IS NULL")
    
    op.alter_column('servicio', 'proveedor_id',
               existing_type=sa.Integer(),
               nullable=False)

    op.create_foreign_key('fk_servicio_proveedor_id', 'servicio', 'usuario', ['proveedor_id'], ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###