"""Añadir fecha_creacion al modelo Servicio

Revision ID: 7dd5bc06ca7e
Revises: 711fb62304c6
Create Date: 2025-11-03 14:39:03.615642

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '7dd5bc06ca7e'
down_revision = '711fb62304c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    op.execute(
        sa.text(f"UPDATE servicio SET fecha_creacion = '{datetime.now()}' WHERE fecha_creacion IS NULL")
    )
    
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
                              existing_type=sa.DateTime(),
                              nullable=False,
                              existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
