"""empty message

Revision ID: 87e57e5fd630
Revises: bc589a981b2b
Create Date: 2025-11-13 17:04:00.723204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e57e5fd630'
down_revision = 'bc589a981b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
