"""Añadir soporte para respuestas anidadas en Posteo

Revision ID: a3e30ff9777c
Revises: 
Create Date: 2025-10-13 20:20:51.483504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e30ff9777c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posteo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posteo_padre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posteo', ['posteo_padre_id'], ['posteo_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posteo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('posteo_padre_id')

    # ### end Alembic commands ###
