"""empty message

Revision ID: afba3e6f230b
Revises: 7dd5bc06ca7e
Create Date: 2025-11-09 22:42:54.349926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afba3e6f230b'
down_revision = '7dd5bc06ca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordenadas', sa.String(length=50), nullable=True))
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('coordenadas')

    # ### end Alembic commands ###
