"""empty message

Revision ID: bc589a981b2b
Revises: afba3e6f230b
Create Date: 2025-11-13 14:50:46.492990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc589a981b2b'
down_revision = 'afba3e6f230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=True),
    sa.Column('fecha_servicio_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_servicio_fin', sa.Date(), nullable=False),
    sa.Column('cantidad_personas', sa.Integer(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.cotizacion_id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.servicio_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('reserva_id'),
    sa.UniqueConstraint('cotizacion_id')
    )
    with op.batch_alter_table('destino', schema=None) as batch_op:
        batch_op.alter_column('coordenadas',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destino', schema=None) as batch_op:
        batch_op.alter_column('coordenadas',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.drop_table('reserva')
    # ### end Alembic commands ###
