"""empty message

Revision ID: fe12d1af8225
Revises: 87e57e5fd630
Create Date: 2025-11-13 20:22:05.524938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe12d1af8225'
down_revision = '87e57e5fd630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=False))
        batch_op.drop_column('fecha_fin_viaje')
        batch_op.drop_column('fecha_inicio_viaje')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio_viaje', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_fin_viaje', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
